services:
  webserver:
    image: php:8.5.8-apache
    ports:
      - "80:80"
    volumes:
      - "./projects:/var/www/html"
      - "./docker/apache/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf:ro"